<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework> #wdawd
    <RootNamespace>DEFENDUDE.Web</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="src\**\*.cs" />
    <EmbeddedResource Remove="src\**\*" />
    <None Remove="src\**\*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="src\DEFENDUDE.Application\DEFENDUDE.Application.csproj" />
    <ProjectReference Include="src\DEFENDUDE.Infrastructure\DEFENDUDE.Infrastructure.csproj" />
  </ItemGroup>

</Project>
